### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by power-guard** [power-guard/pg_monitor_dashboard#28]
## Description
`npm run build` fails on branch `feature/styles-3`.

## Additional context

```
10:04:03 ~/Documents/pg_monitor_dashboard$ npm run build

> pg_monitor_dashboard@0.1.0 build /home/dliberat/Documents/pg_monitor_dashboard
> next build

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Creating an optimized production build  
Failed to compile.

./src/styles/index.css
TypeError: Object.entries(...).flatMap is not a function
    at Array.forEach (<anonymous>)


> Build error occurred
Error: > Build failed because of webpack errors
    at /home/dliberat/Documents/pg_monitor_dashboard/node_modules/next/dist/build/index.js:15:918
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pg_monitor_dashboard@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pg_monitor_dashboard@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dliberat/.npm/_logs/2021-03-01T01_04_52_296Z-debug.log
```

Contents of `2021-03-01T01_04_52_296Z-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pg_monitor_dashboard@0.1.0~prebuild: pg_monitor_dashboard@0.1.0
6 info lifecycle pg_monitor_dashboard@0.1.0~build: pg_monitor_dashboard@0.1.0
7 verbose lifecycle pg_monitor_dashboard@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle pg_monitor_dashboard@0.1.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dliberat/Documents/pg_monitor_dashboard/node_modules/.bin:/home/dliberat/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle pg_monitor_dashboard@0.1.0~build: CWD: /home/dliberat/Documents/pg_monitor_dashboard
10 silly lifecycle pg_monitor_dashboard@0.1.0~build: Args: [ '-c', 'next build' ]
11 silly lifecycle pg_monitor_dashboard@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle pg_monitor_dashboard@0.1.0~build: Failed to exec build script
13 verbose stack Error: pg_monitor_dashboard@0.1.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid pg_monitor_dashboard@0.1.0
15 verbose cwd /home/dliberat/Documents/pg_monitor_dashboard
16 verbose Linux 5.8.0-44-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error pg_monitor_dashboard@0.1.0 build: `next build`
22 error Exit status 1
23 error Failed at the pg_monitor_dashboard@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jcmtallon** [comment]
Above branch was already merged. 
Could not reproduce the issue in `develop` branch. 
Incidentally, as mentioned in [Readme](https://github.com/power-guard/pg_monitor_dashboard#deployment), to generate a build of static html files, please use `npm run export` instead.

**Comment by power-guard** [comment]
Looks like I was using the incorrect branch. Closed.
